[package]
name = "mxbmm"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "=5.0.1"
eframe = "=0.29.1"
notify = "=6.1.1"
walkdir = "=2.5.0"
zip = { version = "=0.6.6", default-features = false, features = ["deflate"] }
